In [1]:
import pandas as pd

In [2]:
## Carregando a base
df_alunos = pd.read_csv("PDA_2022-2024_1.2_Alunos_Anonimo.csv",
                        sep=';',encoding='cp1252')
df_alunos.info()

<class 'pandas.DataFrame'>
RangeIndex: 34344 entries, 0 to 34343
Data columns (total 9 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   PLANO DE DADOS ABERTOS 2022-2024  34344 non-null  str
 1   Unnamed: 1                        31263 non-null  str
 2   Unnamed: 2                        34343 non-null  str
 3   Unnamed: 3                        34343 non-null  str
 4   Unnamed: 4                        34343 non-null  str
 5   Unnamed: 5                        34343 non-null  str
 6   Unnamed: 6                        34343 non-null  str
 7   Unnamed: 7                        34343 non-null  str
 8   Unnamed: 8                        34343 non-null  str
dtypes: str(9)
memory usage: 2.4 MB

In [4]:
dados = df_alunos.shape
print(f'Linhas no DF: {dados[0]}')
print(f'Colunas no DF: {dados[1]}')

Linhas no DF: 34344
Colunas no DF: 9

### Análise Exploratória

In [3]:
# Primeiras linhas
df_alunos.head()

,PLANO DE DADOS ABERTOS 2022-2024,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8
0,Dados Acadêmicos: Alunos Ingressantes e Conclu...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Ingressante/Concluinte,Matrícula,Nome,Nível de Ensino,Curso,Campus,Situação de Matrícula,Período de Ingresso,Data da Apuração
2,Ingressante,NaN,ACHILLES M S,TÉCNICO INTEGRADO,TÉCNICO DE NÍVEL MÉDIO EM MECATRÔNICA,CAMPUS VARGINHA,ATIVO,2022-0,06/06/22
3,Ingressante,NaN,ADELINO P O,TÉCNICO INTEGRADO,TÉCNICO DE NÍVEL MÉDIO EM ELETROTÉCNICA,CAMPUS NEPOMUCENO,ATIVO,2022-0,06/06/22
4,Ingressante,NaN,ADLER L R,TÉCNICO INTEGRADO,TÉCNICO EM MEIO AMBIENTE,CAMPUS NOVA SUÍÇA,ATIVO,2022-0,06/06/22

In [4]:
## Renomeando colunas
df_alunos = df_alunos.rename(columns=df_alunos.iloc[1])
df_alunos = df_alunos.drop([0,1]).reset_index(drop=True)
df_alunos.head()

,Ingressante/Concluinte,Matrícula,Nome,Nível de Ensino,Curso,Campus,Situação de Matrícula,Período de Ingresso,Data da Apuração
0,Ingressante,NaN,ACHILLES M S,TÉCNICO INTEGRADO,TÉCNICO DE NÍVEL MÉDIO EM MECATRÔNICA,CAMPUS VARGINHA,ATIVO,2022-0,06/06/22
1,Ingressante,NaN,ADELINO P O,TÉCNICO INTEGRADO,TÉCNICO DE NÍVEL MÉDIO EM ELETROTÉCNICA,CAMPUS NEPOMUCENO,ATIVO,2022-0,06/06/22
2,Ingressante,NaN,ADLER L R,TÉCNICO INTEGRADO,TÉCNICO EM MEIO AMBIENTE,CAMPUS NOVA SUÍÇA,ATIVO,2022-0,06/06/22
3,Ingressante,NaN,ADRIANA D O,TÉCNICO INTEGRADO,TÉCNICO EM ELETRÔNICA (SUBSEQUENTE),CAMPUS NOVA SUÍÇA,ATIVO,2022-0,06/06/22
4,Ingressante,NaN,ADRIELLE A P S,TÉCNICO INTEGRADO,TÉCNICO EM HOSPEDAGEM,CAMPUS NOVA SUÍÇA,ATIVO,2022-0,06/06/22

In [5]:
## Verificando valores das colunas
df_alunos.describe()

,Ingressante/Concluinte,Matrícula,Nome,Nível de Ensino,Curso,Campus,Situação de Matrícula,Período de Ingresso,Data da Apuração
count,34342,31262,34342,34342,34342,34342,34342,34342,34342
unique,2,674,30092,5,127,16,188,1187,4
top,Concluinte,20151******,RAFAEL M C,TÉCNICO INTEGRADO,TÉCNICO EM ELETROTÉCNICA,CAMPUS NOVA SUÍÇA,ATIVO,2022-0,8/9/2022
freq,30384,1754,10,22513,1727,13442,2845,2229,28690

In [6]:
### Criando um Df para cada coluna, a fim de analisar os valores únicos de cada coluna

nome_colunas = df_alunos.columns.to_list()

nome_df = nome_colunas.copy()
for nome in nome_df:
    if r'/' in nome:
        i = nome_df.index(nome)
        nome_df[i] = nome_df[i].replace(r"/", "_")

In [7]:
dfs = {}

for coluna in df_alunos.columns:
    dfs[coluna] = (
        df_alunos[coluna]
        .value_counts(dropna=False)
        .reset_index()
    )
    dfs[coluna].columns = [coluna, 'Contagem']

In [8]:
dfs["Ingressante/Concluinte"]

  Ingressante/Concluinte  Contagem
0             Concluinte     30384
1            Ingressante      3958

In [9]:
dfs['Campus']

                   Campus  Contagem
0       CAMPUS NOVA SUÍÇA     13442
1   CAMPUS NOVA GAMELEIRA      6368
2            CAMPUS ARAXÁ      2259
3      CAMPUS DIVINÓPOLIS      2115
4          CAMPUS TIMÓTEO      1798
5       CAMPUS LEOPOLDINA      1762
6          NOVA GAMELEIRA      1553
7         CAMPUS VARGINHA      1477
8       CAMPUS NEPOMUCENO       958
9          CAMPUS CURVELO       915
10             NOVA SUÍÇA       756
11        CAMPUS CONTAGEM       676
12            DIVINÓPOLIS        87
13              GAMELEIRA        74
14                  ARAXÁ        62
15             LEOPOLDINA        40

In [10]:
dfs['Curso']

                                                 Curso  Contagem
0                             TÉCNICO EM ELETROTÉCNICA      1727
1                       ENGENHARIA INDUSTRIAL MECÂNICA      1322
2                       ENGENHARIA INDUSTRIAL ELÉTRICA      1256
3                                TÉCNICO EM ELETRÔNICA      1234
4                               TÉCNICO EM EDIFICAÇÕES      1128
..                                                 ...       ...
122     MESTRADO EM TECNOLOGIA DE PRODUTOS E PROCESSOS        15
123  MESTRADO PROFISSIONAL EM EDUCAÇÃO PROFISSIONAL...        15
124                               TÉCNICO EM  TRÂNSITO        12
125                 DOUTORADO MULTICÊNTRICO EM QUÍMICA         8
126  TÉCNICO EM ELETROMECÂNICA (CONCOMITANTE SEMEST...         6

[127 rows x 2 columns]

In [11]:
dfs['Data da Apuração']

  Data da Apuração  Contagem
0         8/9/2022     28690
1         06/06/22      3080
2         6/9/2022      1694
3         2/9/2022       878

In [12]:
dfs['Matrícula']

       Matrícula  Contagem
0            NaN      3080
1    20151******      1754
2    20161******      1736
3    20121******      1718
4    20131******      1677
..           ...       ...
670   2611******         1
671   1802******         1
672   2627******         1
673   1563******         1
674   2626******         1

[675 rows x 2 columns]

In [13]:
dfs['Nome']

                   Nome  Contagem
0            RAFAEL M C        10
1         GUILHERME M S         8
2             LUCAS S F         8
3             LUCAS C M         8
4           GABRIEL S F         7
...                 ...       ...
30087      THIAGO A D F         1
30088    VINÍCIUS H C B         1
30089       VÍTOR O V R         1
30090  WELLINGTON G S J         1
30091    YASMIM T G D M         1

[30092 rows x 2 columns]

In [14]:
dfs['Nível de Ensino']

     Nível de Ensino  Contagem
0  TÉCNICO INTEGRADO     22513
1          GRADUAÇÃO      9257
2          MESTRADO       1596
3           MESTRADO       728
4          DOUTORADO       248

In [15]:
dfs['Período de Ingresso']

     Período de Ingresso  Contagem
0                 2022-0      2229
1                 2021-0      1688
2                 2019-0      1453
3                 2020-0      1252
4                 2018-0      1142
...                  ...       ...
1182           28/5/2014         1
1183              1999-0         1
1184              1997-0         1
1185              2018-3         1
1186             2016-10         1

[1187 rows x 2 columns]

In [16]:
## Contagem valores com '/'

contagem_dados_inconsistentes = 0
contagem_dados = df_alunos.shape[0]

for i in df_alunos.index:
    valor = df_alunos['Período de Ingresso'][i]

    if r'/' in valor:
        contagem_dados_inconsistentes+=1

percentual_inconsistencia = (contagem_dados_inconsistentes/contagem_dados) * 100

print(f'Contagem de dados inconsistentes: {contagem_dados_inconsistentes}')
print(f'Percentual de dados inconsistentes: {percentual_inconsistencia:.2f}%')

Contagem de dados inconsistentes: 2572
Percentual de dados inconsistentes: 7.49%

É possível excluir os registros que possuem valores *inconsistentes*, pois equivale a somente 7.50% dos dados totais.

In [17]:
dfs['Situação de Matrícula']

    Situação de Matrícula  Contagem
0                   ATIVO      2845
1                  2017-0      1422
2                  2016-0      1421
3                  2012-0      1414
4                  2010-0      1403
..                    ...       ...
183                jul/09         1
184                jan/08         1
185                mar/10         1
186                jan/20         1
187                1970-2         1

[188 rows x 2 columns]

In [18]:
df = df_alunos['Situação de Matrícula'].unique().tolist()
filtro = [nome for nome in df if '-' not in nome and r'/' not in nome]
filtro

['ATIVO', 'CANCELADO', 'TRANCADO', 'NÃO CADASTRADO', 'ESPECIAL', 'REGULAR']

In [19]:
contagem_dados_inconsistentes = 0
contagem_dados = df_alunos.shape[0]

for i in df_alunos.index:
    valor  = df_alunos['Situação de Matrícula'][i]
    if valor not in filtro:
        contagem_dados_inconsistentes += 1

percentual_inconsistencia = (contagem_dados_inconsistentes/contagem_dados) * 100

print(f'Total de dados da amostra: {contagem_dados}')
print(f'Percentual de dados incosistentes {percentual_inconsistencia:.2f}%')

Total de dados da amostra: 34342
Percentual de dados incosistentes 88.47%

In [20]:
df_dados_inconsistentes = df_alunos[~df_alunos['Situação de Matrícula'].isin(filtro)]
df_dados_inconsistentes.describe()

,Ingressante/Concluinte,Matrícula,Nome,Nível de Ensino,Curso,Campus,Situação de Matrícula,Período de Ingresso,Data da Apuração
count,30384,30384,30384,30384,30384,30384,30384,30384,30384
unique,1,673,27101,4,119,15,182,1182,2
top,Concluinte,20151******,RAFAEL M C,TÉCNICO INTEGRADO,TÉCNICO EM ELETROTÉCNICA,CAMPUS NOVA SUÍÇA,2017-0,2021-0,8/9/2022
freq,30384,1754,9,20637,1635,12199,1422,1688,28690

In [21]:
df_dados_inconsistentes

,Ingressante/Concluinte,Matrícula,Nome,Nível de Ensino,Curso,Campus,Situação de Matrícula,Período de Ingresso,Data da Apuração
3958,Concluinte,20111******,ABELARDO B A,MESTRADO,MESTRADO EM EDUCAÇÃO TECNOLÓGICA,NOVA GAMELEIRA,jan/11,26/9/2012,6/9/2022
3959,Concluinte,20195******,ABLAIL P P,MESTRADO,MESTRADO EM ENGENHARIA CIVIL,NOVA GAMELEIRA,fev/19,30/8/2021,6/9/2022
3960,Concluinte,20142******,ABRAAO M T,MESTRADO,MESTRADO EM MODELAGEM MATEMÁTICA E COMPUTACIONAL,NOVA GAMELEIRA,out/14,24/2/2017,6/9/2022
3961,Concluinte,20052******,ADALCI R V,MESTRADO,MESTRADO EM EDUCAÇÃO TECNOLÓGICA,NOVA GAMELEIRA,ago/05,18/12/2007,6/9/2022
3962,Concluinte,20141******,ADELI F N,MESTRADO,MESTRADO EM EDUCAÇÃO TECNOLÓGICA,NOVA GAMELEIRA,mar/14,31/3/2016,6/9/2022
...,...,...,...,...,...,...,...,...,...
34337,Concluinte,20131******,VINÍCIUS H C B,GRADUAÇÃO,ENGENHARIA CIVIL,CAMPUS CURVELO,2013-1,2019-2,8/9/2022
34338,Concluinte,20183******,VÍTOR O V R,GRADUAÇÃO,ENGENHARIA CIVIL,CAMPUS CURVELO,2018-1,2021-4,8/9/2022
34339,Concluinte,20122******,WELLINGTON G S J,GRADUAÇÃO,ENGENHARIA CIVIL,CAMPUS CURVELO,2012-2,2017-2,8/9/2022
34340,Concluinte,20131******,YASMIM T G D M,GRADUAÇÃO,ENGENHARIA CIVIL,CAMPUS CURVELO,2013-1,2020-4,8/9/2022
34341,Concluinte,20172******,ZULINA M D C S,GRADUAÇÃO,ENGENHARIA CIVIL,CAMPUS CURVELO,2017-2,2021-4,8/9/2022

Alterar valores da coluna *Situação Matrícula*, dos alunos *Concluinte* para *Formando*.

Aplicando edições no df original.

In [22]:
## Selecionando as colunas pertinentes
df_dados_editados = df_alunos.iloc[:,[0,2,3,4,5,6,7]]

## Alterando o valor das linhas com valores inconsistentes na coluna Situação de Matrícula
df_dados_editados.loc[
    ~df_dados_editados['Situação de Matrícula'].isin(filtro),
    'Situação de Matrícula'   
] = "FORMANDO"


## Apagar linhas com valores inconsistentes na coluna Período de Ingresso
df_dados_editados = df_dados_editados.iloc[~df_dados_editados['Período de Ingresso'].str.contains(r'/',regex=False)].reset_index(drop=True)

## Imprimindo DF
df_dados_editados

,Ingressante/Concluinte,Nome,Nível de Ensino,Curso,Campus,Situação de Matrícula,Período de Ingresso
0,Ingressante,ACHILLES M S,TÉCNICO INTEGRADO,TÉCNICO DE NÍVEL MÉDIO EM MECATRÔNICA,CAMPUS VARGINHA,ATIVO,2022-0
1,Ingressante,ADELINO P O,TÉCNICO INTEGRADO,TÉCNICO DE NÍVEL MÉDIO EM ELETROTÉCNICA,CAMPUS NEPOMUCENO,ATIVO,2022-0
2,Ingressante,ADLER L R,TÉCNICO INTEGRADO,TÉCNICO EM MEIO AMBIENTE,CAMPUS NOVA SUÍÇA,ATIVO,2022-0
3,Ingressante,ADRIANA D O,TÉCNICO INTEGRADO,TÉCNICO EM ELETRÔNICA (SUBSEQUENTE),CAMPUS NOVA SUÍÇA,ATIVO,2022-0
4,Ingressante,ADRIELLE A P S,TÉCNICO INTEGRADO,TÉCNICO EM HOSPEDAGEM,CAMPUS NOVA SUÍÇA,ATIVO,2022-0
...,...,...,...,...,...,...,...
31765,Concluinte,VINÍCIUS H C B,GRADUAÇÃO,ENGENHARIA CIVIL,CAMPUS CURVELO,FORMANDO,2019-2
31766,Concluinte,VÍTOR O V R,GRADUAÇÃO,ENGENHARIA CIVIL,CAMPUS CURVELO,FORMANDO,2021-4
31767,Concluinte,WELLINGTON G S J,GRADUAÇÃO,ENGENHARIA CIVIL,CAMPUS CURVELO,FORMANDO,2017-2
31768,Concluinte,YASMIM T G D M,GRADUAÇÃO,ENGENHARIA CIVIL,CAMPUS CURVELO,FORMANDO,2020-4
31769,Concluinte,ZULINA M D C S,GRADUAÇÃO,ENGENHARIA CIVIL,CAMPUS CURVELO,FORMANDO,2021-4

In [23]:
## Exportando Dados Editados CSV
df_dados_editados.to_csv('dados_editados.csv', index=False)